apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - mlflow-deployment.yaml
  - mlflow-service.yaml
  - api-deployment.yaml
  - api-service.yaml

commonLabels:
  environment: development
  project: mlops-forecasting