apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mlflow-deployment.yaml
  - mlflow-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml

commonLabels:
  environment: production
  project: mlops-forecasting